#############################################################################
# Makefile for building: hdspmidi
# Generated by qmake (2.01a) (Qt 4.8.1) on: qui Set 6 17:45:10 2012
# Project:  hdspmidi.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile hdspmidi.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -m64 -pipe -g -O0 -Wall -W  $(DEFINES)
CXXFLAGS      = -m64 -pipe -g -O0 -Wall -W  $(DEFINES)
INCPATH       = -Isrc -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/x86_64-linux-gnu -lasound -lconfig++ -lpthread 
AR            = ar cqs
RANLIB        = 
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/Channel.cpp \
		src/channelmap.cxx \
		src/HDSPMixerCard.cxx \
		src/midicontroller.cpp \
		src/bridge.cpp \
		src/midi.cpp 
OBJECTS       = Channel.o \
		channelmap.o \
		HDSPMixerCard.o \
		midicontroller.o \
		bridge.o \
		midi.o

DESTDIR       = 
TARGET        = hdspmidi

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

dist: 
	@$(CHK_DIR_EXISTS) .tmp/hdspmidi1.0.0 || $(MKDIR) .tmp/hdspmidi1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/hdspmidi1.0.0/ && $(COPY_FILE) --parents src/Channel.h src/channelmap.h src/HDSPMixerCard.h .tmp/hdspmidi1.0.0/ && $(COPY_FILE) --parents src/Channel.cpp src/channelmap.cxx src/HDSPMixerCard.cxx src/midi.cpp .tmp/hdspmidi1.0.0/ && (cd `dirname .tmp/hdspmidi1.0.0` && $(TAR) hdspmidi1.0.0.tar hdspmidi1.0.0 && $(COMPRESS) hdspmidi1.0.0.tar) && $(MOVE) `dirname .tmp/hdspmidi1.0.0`/hdspmidi1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/hdspmidi1.0.0


clean:
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first


####### Compile

Channel.o: src/Channel.cpp src/Channel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Channel.o src/Channel.cpp

midicontroller.o: src/midicontroller.cpp src/midicontroller.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o midicontroller.o src/midicontroller.cpp

bridge.o: src/bridge.cpp src/bridge.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o bridge.o src/bridge.cpp

channelmap.o: src/channelmap.cxx src/channelmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o channelmap.o src/channelmap.cxx

HDSPMixerCard.o: src/HDSPMixerCard.cxx src/HDSPMixerCard.h \
		src/channelmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o HDSPMixerCard.o src/HDSPMixerCard.cxx

midi.o: src/midi.cpp src/HDSPMixerCard.h \
		src/channelmap.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o midi.o src/midi.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

